### ISSUE TITLE
Agate not properly starting because of wrong keystore password

### ISSUE THREAD

**Issue by ymarcon** [obiba/agate#287]
As reported by Vincent Sirois:

Hi! I've been working since last week on setting up a Obiba software stack (Mica2, Opal & Agate). Most services seems to run fine as of right now but I still have many issues with Agate.
Both dependencies, Java JRE & mongodb are available and working. I don't have a password for mongodb yet, but I will add one in the future.

```
Unable to find source-code formatter for language: bash. Available languages are: actionscript, html, java, javascript, none, sql, xhtml, xml
$ mongod --version
db version v2.6.12
2018-06-07T15:38:10.323-0400 git version: nogitversion
2018-06-07T15:38:10.323-0400 OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
```

All services such as Opal, Mica2, Mica2 drupal & Agate are all running on the same server.

I've also tried to start the agate process as root instead of with the usual agate service user but I still got the same error in the log.

I've also added the agate log as an attachment.If you need more information please feel free to ask and I'll answer them as swiftly as possible.

[agate_log.txt](https://github.com/obiba/agate/files/2083960/agate_log.txt)

**Comment by ymarcon** [comment]
As reported by Vincent Sirois:

Here's some more information.
my application.yml file:

```
server:
    port: 8081
    address: localhost

https:
    port: 8444

spring:
    profiles: prod
    data:
        mongodb:
            uri: mongodb://localhost:27017/agate
    mail:
        host: localhost
        port: 25
        user:
        password:
        protocol: smtp
        tls: false
        auth: false
        from: agate@example.org

shiro:
    password:
        nbHashIterations: 10000
        salt: agate

registration:
    pendingForApprovalSubject: Account Registration
    pendingForReviewSubject: Registration Pending
    confirmationSubject: Registration Approved
    resetPasswordSubject: Password Reset
    forgotUsernameSubject: Account Login Details

recaptcha:
    verifyUrl: https://www.google.com/recaptcha/api/siteverify
    secret: -- captcha here --

client:
    reCaptchaKey: -- captcha here --
```

I also forgot to point out that my main issue right now is that both localhost for both http and https are not working.
