### ISSUE TITLE
error 500 with oauth2

### ISSUE THREAD

**Issue by tdemalliard** [obiba/agate#478]
**Describe the bug**
When accepted permission for openid, one get a 500 html error.

**To Reproduce**
1. configur openid app with  :
```
  auth_url: https://agate.cartagene.qc.ca/authorize
  token_url: https://agate.cartagene.qc.ca/ws/oauth2/token
  user_info_url: https://agate.cartagene.qc.ca/ws/oauth2/userinfo
  scopes:
    - openid
    - email
    - profile
```
2. login on mica2
3. click to go to openid protected app
4. protected app send back to agate for identification with link `https://agate.cartagene.qc.ca/authorize?client_id=openid&redirect_uri=https%3A%2F%2Fopenid.cartagene.qc.ca%2Fauth&response_type=code&scope=openid+email+profile&state=agoiQO96Wek6AA1EndxlJN7IshmHIa` 
5. agate show fhe form permissions 
6. Accept (or decline) lead to error 500 and authorization does not appear in mongodb

And these are the steps that work: 
1. open incognito chrome session
2. DO NOT login on mica2
3. Instead, click on openid protected app link 
4. app redirects to agate for login
5. login
6. agate redirects to app WITHOUT accepting openid permissions, neither shoing them.
7. app accepts the openid otken and shows the material

**Expected behavior**
Authorization is given upon after giving the permissions, no error 500.

**Screenshots**
Agate persmission form to accept
![image](https://user-images.githubusercontent.com/3911087/158244319-e3d48b2e-6e9d-4716-b08e-cf9ec1009fa2.png)

Agate error 500 after clicking on accepting.
![image](https://user-images.githubusercontent.com/3911087/158244445-d1c109a7-3f29-4c56-bd2c-ec73369c4efe.png)

**Desktop (please complete the following information):**
 - OS: macos and windows 10
 - Browser chrome
 - up to date versions
 - agate 2.5.3

**Additional context**
On a side note, agate documentation show `https://agate.example.org/ws/oauth2/authorize`  (https://agatedoc.obiba.org/en/latest/oauth2-api/authorization-code-grant-flow.html)

But I had to use `https://agate.cartagene.qc.ca/authorize` to make it work somehow.
